### ISSUE TITLE
[Bug report] Support for Android network debugging

### ISSUE THREAD

**Issue by s-kk** [ninthDevilHAUNSTER/ArknightsAutoHelper#20]
Android Device: Lineage OS 15.1
PC: Windows 7 Pro
Python dependencies are all installed.

Dear developer!
  My current PC is not capable for using a Android Emu, so I decided to try with my Android phone with network debugging enabled.
  But when I change ADB_HOST in the configuration files (default_setting.json and common_config.py), none of them worked. Both reported "[96m[!] 检测到多台设备，根据 ADB_HOST 参数将自动选择设备[0m, 自动选择设备失败，请根据上述内容自行输入数字并选择" in my cmd console.
  Is there any lack of support for real Android devices connected via USB or just network debugging?
  Thanks!

**Comment by ninthDevilHAUNSTER** [comment]
Thanks for reporting issue!

I am sorry to tell you that my script is only support for the android device with  dpi 1280*720, so I strongly recommend to use a Android Emu.

What's more I view that the adb cannot detect your device, you should switch on the Developer options
and usb debugging. If success,  you can see the out put like that ,which  contains the device ID of your Android phone. 

```python
[!] 检测到多台设备，根据 ADB_HOST 参数将自动选择设备
[*]  0	3HXKK17406600105	device
[*]  1	127.0.0.1:62001	device
自动选择设备失败，请根据上述内容自行输入数字并选择
>0
[+] 确认设备名称	3HXKK17406600105
[+] 战斗-选择GT-6...启动！
```

To ensure your device is connected , we can run cmd like that to see if your device is successfully connected
```shell
D:\Program Files\Nox\bin # the root which contains adb.exe ,which is the value of  ADB_ROOT
λ .\adb.exe devices
List of devices attached
3HXKK17406600105        device
127.0.0.1:62001 device
```

**Comment by s-kk** [comment]
Both USB debugging and network debugging has been switched on before the test.
If I connect directly to my phone, what configuration should I fill in the json file?

**Comment by ninthDevilHAUNSTER** [comment]
If your are not sure how to fill in the ADB_HOST, you can set it as an empty string . (In my case , I didn't know my USB debugging id is  `3HXKK17406600105` , but the script can detect it .)The class ADBShell can auto detect all the host and you can choose which HOST to connect .(function `__adb_device_name_detector`)

Otherwise , the project is still in development , I discussed with my users and they think use python script as config file is better . So if you pull the newest verison, you need to change the ADB_ROOT in `config/developer_config.py` rather than `config/default_setting.json`. But I still leave the port for JSON file , which you can find in `config/__init__.py`

Thanks for reporting 😄
